Repository codestates-seb/seb43_main_006, pull requests merged in 2023-05, with the labels that each got.

#36 Fix: ts 버전 다운그레이드 및 초기 세팅 수정
  client/package-lock.json
  client/package.json
  client/src/.eslintrc.json
  client/src/assets/Data.ts
  client/src/components/Common/Buttons.tsx
  client/src/hooks/UseAxios.ts
  client/src/redux/index.ts
Labels: FE, 🐞BugFix

#39 Fix: eslint 에러 수정(최종)
  client/.eslintrc.json
  client/package-lock.json
  client/src/hooks/ useAxios.tsx
  client/src/layout/Header/index.tsx
  client/src/layout/Main/index.tsx
  client/src/pages/Alcohol.tsx
  client/src/pages/AlcoholDetail.tsx
  client/src/pages/Cart.tsx
  client/src/pages/HelpCenter.tsx
  client/src/pages/Home.tsx
  client/src/pages/Mypage.tsx
  client/src/pages/Payment/Payment.tsx
  client/src/pages/Payment/PaymentConfirm.tsx
  client/src/pages/Place.tsx
  client/src/pages/Signup.tsx
  client/src/redux/slice/store.tsx
  client/src/styles/GlobalStyle.ts
  client/src/styles/theme.ts
Labels: FE, 🐞BugFix

#47 feat: Header 구현
  client/package-lock.json
  client/package.json
  client/src/assets/images/Logo.svg
  client/src/assets/images/Maintop.png
  client/src/custom.d.ts
  client/src/hooks/UseHover.ts
  client/src/layout/Header/index.tsx
Labels: FE, 🔥Feature, 🎨HTML&CSS

#53 Feat: 기타 로그인-회원가입 페이지 관련 변경 및 추가사항
  client/src/assets/images/facebook.png
  client/src/assets/images/google.png
  client/src/assets/images/login-bg.png
  client/src/components/Common/Button.tsx
  client/src/components/Common/Buttons.tsx
  client/src/types/Interfaces.ts
Labels: FE, 🔥Feature

#59 Feat: 주류 리스트 페이지 레이아웃 구현
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/assets/Data.ts
  client/src/assets/images/alcohol.jpeg
  client/src/components/AlcoholPage/AlcoholList.tsx
  client/src/components/AlcoholPage/AlcoholListItem.tsx
  client/src/components/Common/PriceRegular.tsx
  client/src/components/Common/ReviewRating.tsx
  client/src/hooks/useAxios.tsx
  client/src/pages/Alcohol.tsx
  client/src/pages/AlcoholDetail.tsx
  client/src/styles/theme.ts
  client/src/types/AlcholInterfaces.ts
Labels: FE, 🔥Feature, 🎨HTML&CSS

#62 feat : 메일 보내는 형식을 html로 구현 + 이쁘게 보내도록 수정
  server/src/main/java/com/codestates/julsinsa/helper/email/EmailConfiguration.java
  server/src/main/java/com/codestates/julsinsa/helper/email/HtmlEmailSendable.java
  server/src/main/java/com/codestates/julsinsa/helper/event/MemberRegistrationEventListener.java
  server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java
Labels: BE, 🔥Feature

#61 Design: 주류 상세 페이지 구매 부분 레이아웃 구성
  client/src/assets/images/alcohol.jpeg
  client/src/assets/images/alcohol.png
  client/src/components/AlcoholDetailPage/AlcoholItem.tsx
  client/src/components/AlcoholPage/AlcoholListItem.tsx
  client/src/components/Common/ClickFavoriteItem.tsx
  client/src/pages/AlcoholDetail.tsx
  client/src/styles/GlobalStyle.ts
Labels: FE, 🔥Feature, 🎨HTML&CSS

#87 Feat: 주류 리스트 페이지 pagination 구현
  client/src/components/AlcoholPage/AlcoholList.tsx
  client/src/components/AlcoholPage/AlcoholListItem.tsx
  client/src/components/AlcoholPage/Pagination.tsx
  client/src/hooks/useAxios.tsx
  client/src/types/AlcholInterfaces.ts
Labels: FE, 🔥Feature

#97 Fix: 찜 목록 불러오는 데이터 추가 , 유효성 규칙 추가 , 유효성 예외 처리 로직 추가
  server/src/main/java/com/codestates/julsinsa/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/julsinsa/item/controller/ItemController.java
  server/src/main/java/com/codestates/julsinsa/item/dto/ItemDto.java
  server/src/main/java/com/codestates/julsinsa/item/entity/Item.java
  server/src/main/java/com/codestates/julsinsa/item/mapper/ItemMapper.java
  server/src/main/java/com/codestates/julsinsa/item/repository/FavoriteRepository.java
  server/src/main/java/com/codestates/julsinsa/item/repository/ItemRepository.java
  server/src/main/java/com/codestates/julsinsa/item/service/ItemService.java
  server/src/main/java/com/codestates/julsinsa/member/controller/MemberController.java
  server/src/main/java/com/codestates/julsinsa/member/dto/EmailRequest.java
  server/src/main/java/com/codestates/julsinsa/member/dto/FindDto.java
  server/src/main/java/com/codestates/julsinsa/member/dto/MemberDto.java
  server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java
  server/src/main/java/com/codestates/julsinsa/response/ErrorResponse.java
  server/src/main/java/com/codestates/julsinsa/review/dto/ReviewDto.java
  server/src/main/java/com/codestates/julsinsa/review/mapper/ReviewMapper.java
  server/src/main/java/com/codestates/julsinsa/review/service/ReviewService.java
  server/src/main/resources/db/h2/data.sql
Labels: BE

#100 Design: 마이페이지 전체적인 디자인 변경
  client/src/App.tsx
  client/src/pages/Mypage/buyend.tsx
  client/src/pages/Mypage/changeinfo.tsx
  client/src/pages/Mypage/infochange.tsx
  client/src/pages/Mypage/likepage.tsx
  client/src/pages/Mypage/notmember.tsx
  client/src/pages/Mypage/orderpage.tsx
Labels: FE, 🔥Feature, 🎨HTML&CSS

#104 Fix: 주류 리스트 레이아웃 수정
  client/src/components/AlcoholPage/AlcoholList.tsx
  client/src/components/AlcoholPage/AlcoholListItem.tsx
  client/src/pages/Alcohol.tsx
  client/src/types/AlcholInterfaces.ts
Labels: FE, 🐞BugFix

#110 Feat: 주류 리스트 정렬 드롭다운 메뉴 구현
  client/src/components/AlcoholPage/AlcoholList.tsx
  client/src/components/AlcoholPage/SortingUtils.tsx
  client/src/hooks/useAxios.tsx
  client/src/pages/Alcohol.tsx
  client/src/types/AlcholInterfaces.ts
Labels: FE, 🔥Feature

#112 Feat: 찜리스트 페이지 페이지네이션 구현 및 개인정보수정페이지 에러수정 및 기능 추가
  client/src/pages/Mypage/changeinfo.tsx
  client/src/pages/Mypage/likepage.tsx
Labels: FE, 🔥Feature, 🐞BugFix

#115 Refector: 주류 리스트 페이지 API 요청 인스턴스화
  client/src/hooks/useAxios.tsx
  client/src/pages/Alcohol.tsx
  client/src/services/api/alcoholListAPI.ts
  client/src/services/api/index.ts
Labels: FE, 🛠Refector, 📬API

#116 Feat: 장바구니 페이지 구현
  client/src/components/Common/Button.tsx
  client/src/pages/Cart.tsx
  client/src/types/Interfaces.ts
Labels: FE, 🔥Feature, 🎨HTML&CSS

#117 Feat: 카카오맵 지도 연결
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/pages/Map.tsx
  client/src/pages/Mypage/likepage.tsx
  client/src/pages/Place.tsx
Labels: FE, 🔥Feature

#124 Feat: 장바구니 추가
  server/src/main/java/com/codestates/julsinsa/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/julsinsa/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/codestates/julsinsa/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/codestates/julsinsa/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/julsinsa/cart/controller/CartController.java
  server/src/main/java/com/codestates/julsinsa/cart/dto/CartDto.java
  server/src/main/java/com/codestates/julsinsa/cart/dto/ItemCartDto.java
  server/src/main/java/com/codestates/julsinsa/cart/entity/Cart.java
  server/src/main/java/com/codestates/julsinsa/cart/entity/ItemCart.java
  server/src/main/java/com/codestates/julsinsa/cart/mapper/CartMapper.java
  server/src/main/java/com/codestates/julsinsa/cart/repository/CartRepository.java
  server/src/main/java/com/codestates/julsinsa/cart/service/CartService.java
  server/src/main/java/com/codestates/julsinsa/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/julsinsa/exception/ExceptionCode.java
  server/src/main/java/com/codestates/julsinsa/item/controller/ItemController.java
  server/src/main/java/com/codestates/julsinsa/item/entity/Item.java
  server/src/main/java/com/codestates/julsinsa/item/repository/ItemRepository.java
  server/src/main/java/com/codestates/julsinsa/item/service/ItemService.java
  server/src/main/java/com/codestates/julsinsa/member/controller/MemberController.java
  server/src/main/java/com/codestates/julsinsa/member/dto/MemberDto.java
  server/src/main/java/com/codestates/julsinsa/member/entity/Member.java
  server/src/main/java/com/codestates/julsinsa/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java
  server/src/main/resources/db/h2/data.sql
Labels: BE, 🔥Feature

#122 Feat: 지도페이지 검색기능 구현
  client/public/index.html
  client/src/pages/Map.tsx
  client/src/pages/Place.tsx
Labels: FE, 🔥Feature

#125 Feat: useAxiosAll 에러 상태 확인후 토큰 갱신 및 재요청 로직 추가
  client/src/App.tsx
  client/src/hooks/useAxiosAll.ts
  client/src/pages/Login/FindEmail.tsx
  client/src/pages/Login/FindPassword.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Mypage/changeinfo.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/redux/slice/store.tsx
Labels: FE, 🔥Feature, 🐞BugFix

#128 Feat: 주류 상세데이터 결제 페이지 props 전달
  client/src/components/AlcoholDetailPage/AlcoholItem.tsx
  client/src/components/AlcoholDetailPage/QuantityControl.tsx
  client/src/pages/AlcoholDetail.tsx
  client/src/services/api/alcoholListAPI.ts
  client/src/types/AlcholInterfaces.ts
Labels: FE, 🔥Feature

#131 Feat: Oauth 2 인증 로직 및 상태관리 추가 및 기타 분기 변경
  client/src/components/Common/AlertModal.tsx
  client/src/pages/Login/FindEmail.tsx
  client/src/pages/Login/FindPassword.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Mypage/changeinfo.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/pages/Signup/SignupSelection.tsx
  client/src/pages/Signup/SignupTerm.tsx
  client/src/types/Interfaces.ts
Labels: FE, 🔥Feature, 🐞BugFix

#132 Feat: 모달 공통 컴포넌트 구현 및 기능 추가
  client/src/components/Common/AlertModal.tsx
  client/src/pages/Login/FindPassword.tsx
  client/src/types/Interfaces.ts
Labels: FE, 🔥Feature, 🎨HTML&CSS

#136 Feat: 주류 아이템 찜 구현
  client/src/components/AlcoholDetailPage/AlcoholItem.tsx
  client/src/components/AlcoholPage/AlcoholListItem.tsx
  client/src/components/Common/ClickFavoriteItem.tsx
  client/src/services/api/alcoholListAPI.ts
  client/src/services/api/axiosInstance.ts
  client/src/types/AlcholInterfaces.ts
Labels: FE, 🔥Feature, 🐞BugFix, 🛠Refector

#139 Feat: 지도페이지 사용자 현재위치조회 및 커스텀어레이 기능 추가
  client/src/pages/Map.tsx
  client/src/pages/MarkerData.js
  client/src/pages/Place.tsx
Labels: FE, 🔥Feature

#138 Feat: Oauth 인증 로직 추가 및 수정 그리고 기타 관련 코드 정리
  client/src/components/SignupTerm/Term.tsx
  client/src/hooks/useAxiosAll.ts
  client/src/hooks/useAxiosAll.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Mypage/changeinfo.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/pages/Signup/SignupTerm.tsx
Labels: FE, 🔥Feature, 🐞BugFix, 🎨HTML&CSS

#143 feat: 결제페이지 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/pages/Payment/Checkout.tsx
  client/src/pages/Payment/Fail.tsx
  client/src/pages/Payment/Payment.tsx
  client/src/pages/Payment/PaymentUserinfo.tsx
  client/src/pages/Payment/Paymentitemlist.tsx
  client/src/pages/Payment/Paymentpayinfo.tsx
  client/src/pages/Payment/Progress.tsx
  client/src/types/AlcholInterfaces.ts
Labels: FE, 🔥Feature

#144 Feat: 주류 상세 페이지 구현
  client/src/components/AlcoholDetailPage/AlcohoIItemReview.tsx
  client/src/components/AlcoholDetailPage/AlcohoItemContent.tsx
  client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
  client/src/components/AlcoholPage/AlcoholListItem.tsx
  client/src/pages/AlcoholDetail.tsx
  client/src/services/api/axiosInstance.ts
  client/src/types/AlcholInterfaces.ts
Labels: FE, 🔥Feature, 🐞BugFix, 🎨HTML&CSS

#146 Feat: GPT 컴포넌트 구현 및 오어스 인증 로직 수정
  client/src/App.tsx
  client/src/assets/gif/spinner.gif
  client/src/components/Chat/ChatComponent.tsx
  client/src/hooks/useAxiosAll.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/pages/Signup/SignupSelection.tsx
Labels: FE, 🔥Feature, 🐞BugFix, 🎨HTML&CSS

#148 Fix: 상세 페이지 추천 상품 화살표 스크롤 수정
  client/src/components/AlcoholDetailPage/AlcohoItemContent.tsx
  client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
  client/src/components/AlcoholPage/AlcoholListItem.tsx
  client/src/components/Common/PriceDisplay.tsx
  client/src/components/Common/PriceRegular.tsx
  client/src/utils/priceUtils.ts
Labels: FE, 🐞BugFix

#149 Feat: 지도페이지 매장선택 구현
  client/src/pages/Map.tsx
  client/src/pages/Place.tsx
  client/src/redux/slice/store.tsx
Labels: FE, 🔥Feature

#152 Refactor: 주류 리스트 카테고리 및 주류 API 인스턴스 리팩토링
  client/src/components/AlcoholPage/SortingUtils.tsx
  client/src/services/api/alcoholListAPI.ts
Labels: FE, 🛠Refector

#153 Feat: alias path 설정 및 적용
  client/.eslintrc.json
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Chat/ChatComponent.tsx
  client/src/hooks/useAxiosAll.tsx
  client/src/pages/Login/FindEmail.tsx
  client/src/pages/Login/FindPassword.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Mypage/changeinfo.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/pages/Signup/SignupTerm.tsx
  client/tsconfig.json
  client/tsconfig.paths.json
Labels: FE, 🔥Feature, 🛠Refector

#154 fix: 결제 상태끌어올리기 수정
  client/package-lock.json
  client/package.json
  client/src/pages/Payment/Checkout.tsx
  client/src/pages/Payment/Fail.tsx
  client/src/pages/Payment/Payment.tsx
  client/src/pages/Payment/PaymentConfirm.tsx
  client/src/pages/Payment/PaymentUserinfo.tsx
Labels: FE, 🔥Feature, 🛠Refector

#155 Fix: Alias Craco 버그 수정
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/tsconfig.json
Labels: FE, 🐞BugFix

#157 Fix: 결제 창으로 변경
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/pages/Payment/Checkout.tsx
  client/src/pages/Payment/CheckoutChang.tsx
  client/src/pages/Payment/Payment.tsx
  client/src/pages/Payment/PaymentConfirm.tsx
  client/src/pages/Payment/PaymentUserinfo.tsx
  client/src/pages/Payment/Progress.tsx
Labels: 🐞BugFix

#159 fix: 토큰 저장 및 사용 방식 수정
  client/src/hooks/useAxiosAll.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login/Login.tsx
Labels: FE, 🛠Refector

#160 Fix: 기존 로그인과 OAuth2 로그인 토큰 만료시간,발행시간 형식 수정 , 유효성 규칙 추가
  server/src/main/java/com/codestates/julsinsa/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/julsinsa/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/codestates/julsinsa/cart/mapper/CartMapper.java
  server/src/main/java/com/codestates/julsinsa/item/dto/ItemDto.java
  server/src/main/java/com/codestates/julsinsa/item/entity/Favorite.java
  server/src/main/java/com/codestates/julsinsa/item/entity/Item.java
  server/src/main/java/com/codestates/julsinsa/item/repository/FavoriteRepository.java
  server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java
  server/src/main/java/com/codestates/julsinsa/order/entity/Order.java
  server/src/main/java/com/codestates/julsinsa/review/dto/ReviewDto.java
  server/src/main/java/com/codestates/julsinsa/review/repository/ReviewRepository.java
  server/src/main/java/com/codestates/julsinsa/review/service/ReviewService.java
  server/src/main/resources/application.yml
  server/src/main/resources/db/h2/data.sql
Labels: BE

#161 Feat: 고객페이지 구현 및 import 경로 수정
  client/src/components/Common/AlertModal.tsx
  client/src/components/Common/Button.tsx
  client/src/components/HelpCenter/AnswerContainer.tsx
  client/src/index.tsx
  client/src/pages/HelpCenter.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login/Login.tsx
Labels: FE, 🔥Feature, 🛠Refector

#162 Fix: Header navigate 및 css 수정
  client/src/layout/Header/index.tsx
  client/src/layout/Main/index.tsx
Labels: 🐞BugFix, 🎨HTML&CSS

#163 Feat: 마이페이지 기능 구현
  client/src/pages/Map.tsx
  client/src/pages/Mypage/likepage.tsx
  client/src/pages/Mypage/orderpage.tsx
Labels: FE, 🔥Feature, 🛠Refector

#166 Feat : 주문내역 추가
  server/src/main/java/com/codestates/julsinsa/image/entity/ItemImage.java
  server/src/main/java/com/codestates/julsinsa/item/entity/Item.java
  server/src/main/java/com/codestates/julsinsa/member/dto/MemberDto.java
  server/src/main/java/com/codestates/julsinsa/order/controller/OrderController.java
  server/src/main/java/com/codestates/julsinsa/order/dto/ItemOrderDto.java
  server/src/main/java/com/codestates/julsinsa/order/dto/OrderDto.java
  server/src/main/java/com/codestates/julsinsa/order/mapper/OrderMapper.java
  server/src/main/java/com/codestates/julsinsa/order/repository/OrderRepository.java
  server/src/main/java/com/codestates/julsinsa/order/service/OrderService.java
  server/src/main/java/com/codestates/julsinsa/review/service/ReviewService.java
  server/src/main/resources/db/h2/data.sql
  server/src/test/java/com/codestates/julsinsa/member/MemberControllerTest.java
Labels: BE, 🔥Feature

#169 Feat: 찜리스트, 주문내역 페이지기능 구현 마무리
  client/src/App.tsx
  client/src/pages/Mypage/likepage.tsx
  client/src/pages/Mypage/orderpage.tsx
  client/src/redux/slice/store.tsx
Labels: FE, 🔥Feature, 🛠Refector

#171 Feat: 멤버 ID 로컬 저장 및 refresh 토큰 만료 시 로컬 저장 삭제 구현
  client/src/hooks/useAxiosAll.tsx
  client/src/pages/HelpCenter.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login/Login.tsx
Labels: FE, 🔥Feature

#172 Rename: 파일명 변경
  client/src/App.tsx
  client/src/pages/Mypage/ChangeInfoPage.tsx
  client/src/pages/Mypage/LikeListPage.tsx
  client/src/pages/Mypage/OrderListPage.tsx
Labels: FE, 🛠Refector

#178 fix: 토큰마다 memberId 헤더에 추가 , OAuth 로그인시 url에 memberId추가 , item 엔티티에 content제거 , 리뷰 수정에도 사진 수정 가능할 수 있게 로직 변경
  server/src/main/java/com/codestates/julsinsa/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/codestates/julsinsa/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/codestates/julsinsa/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/codestates/julsinsa/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/codestates/julsinsa/auth/utills/ErrorResponder.java
  server/src/main/java/com/codestates/julsinsa/cart/controller/CartController.java
  server/src/main/java/com/codestates/julsinsa/cart/service/CartService.java
  server/src/main/java/com/codestates/julsinsa/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/julsinsa/global/audit/Auditable.java
  server/src/main/java/com/codestates/julsinsa/global/dto/MultiResponseDto.java
  server/src/main/java/com/codestates/julsinsa/global/dto/PageInfo.java
  server/src/main/java/com/codestates/julsinsa/global/dto/SingleResponseDto.java
  server/src/main/java/com/codestates/julsinsa/global/exception/BusinessLogicException.java
  server/src/main/java/com/codestates/julsinsa/global/exception/ExceptionCode.java
  server/src/main/java/com/codestates/julsinsa/global/response/ErrorResponse.java
  server/src/main/java/com/codestates/julsinsa/global/utils/UriCreator.java
  server/src/main/java/com/codestates/julsinsa/image/entity/ReviewImage.java
  server/src/main/java/com/codestates/julsinsa/image/service/ImageService.java
  server/src/main/java/com/codestates/julsinsa/item/controller/ItemController.java
  server/src/main/java/com/codestates/julsinsa/item/dto/ItemDto.java
  server/src/main/java/com/codestates/julsinsa/item/entity/Item.java
  server/src/main/java/com/codestates/julsinsa/item/service/ItemService.java
  server/src/main/java/com/codestates/julsinsa/market/service/MarketService.java
  server/src/main/java/com/codestates/julsinsa/member/controller/MemberController.java
  server/src/main/java/com/codestates/julsinsa/member/entity/Member.java
  server/src/main/java/com/codestates/julsinsa/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java
  server/src/main/java/com/codestates/julsinsa/order/entity/Order.java
  server/src/main/java/com/codestates/julsinsa/order/service/OrderService.java
  server/src/main/java/com/codestates/julsinsa/payment/service/PaymentService.java
  server/src/main/java/com/codestates/julsinsa/review/controller/ReviewController.java
  server/src/main/java/com/codestates/julsinsa/review/entity/Review.java
  server/src/main/java/com/codestates/julsinsa/review/service/ReviewService.java
  server/src/main/resources/application.yml
  server/src/main/resources/db/h2/data.sql
Labels: BE, 🔥Feature

#185 !BREAKING CHANGE: 배포 서버 url 변경
  client/src/hooks/useAxiosAll.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/pages/Signup/SignupSelection.tsx
  client/src/pages/Signup/SignupTerm.tsx
Labels: FE, 🌏Deploy

#193 Fix : 이미지 업로드 확장자 추가 , xToOne 연관 관계 LAZY 설정
  server/src/main/java/com/codestates/julsinsa/cart/entity/Cart.java
  server/src/main/java/com/codestates/julsinsa/cart/entity/ItemCart.java
  server/src/main/java/com/codestates/julsinsa/image/entity/ReviewImage.java
  server/src/main/java/com/codestates/julsinsa/image/service/ImageService.java
  server/src/main/java/com/codestates/julsinsa/item/entity/Favorite.java
  server/src/main/java/com/codestates/julsinsa/member/entity/Member.java
  server/src/main/resources/db/h2/data.sql
Labels: BE, 🛠Refector

#194 Fix: 헤더 로그아웃 검증 수정
  client/src/layout/Header/index.tsx
Labels: FE, 🐞BugFix

#190 Feat: 아이템 장바구니 추가
  client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
  client/src/components/AlcoholDetailPage/ReviewList.tsx
  client/src/services/api/cartAPI.ts
  client/src/services/api/index.ts
  client/src/services/api/itemAPI.ts
Labels: FE, 🔥Feature, 📬API

#195 Fix : 결제 기능 완료
  client/src/pages/Cart.tsx
  client/src/pages/Payment/CheckoutChang.tsx
  client/src/pages/Payment/Payment.tsx
  client/src/pages/Payment/PaymentConfirm.tsx
  client/src/pages/Payment/PaymentUserinfo.tsx
  client/src/pages/Payment/Paymentpayinfo.tsx
Labels: FE, 🔥Feature, 🐞BugFix

#197 feat : 술 CRUD 완성
  server/src/main/java/com/codestates/julsinsa/item/controller/ItemController.java
  server/src/main/java/com/codestates/julsinsa/item/dto/ItemDto.java
  server/src/main/java/com/codestates/julsinsa/item/entity/Item.java
  server/src/main/java/com/codestates/julsinsa/item/mapper/ItemMapper.java
  server/src/main/java/com/codestates/julsinsa/item/repository/ItemRepository.java
  server/src/main/java/com/codestates/julsinsa/item/service/ItemService.java
  server/src/main/java/com/codestates/julsinsa/member/controller/MemberController.java
Labels: BE, 🔥Feature

#199 Fix: 반응형 수정 및 로그아웃 상태시 알림 설정
  client/src/components/Chat/ChatComponent.tsx
  client/src/hooks/useAxiosAll.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Mypage/ChangeInfoPage.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/pages/Signup/SignupTerm.tsx
Labels: FE, 🔥Feature, 🐞BugFix, 🎨HTML&CSS

#201 Feat: 헤더 연결주소 변경 및 review연결
  client/src/layout/Header/index.tsx
  client/src/pages/Mypage/LikeListPage.tsx
  client/src/pages/Mypage/OrderListPage.tsx
  client/src/pages/Place.tsx
Labels: FE, 🔥Feature, 🎨HTML&CSS

#202 refactor : 의미 없는 로직 제거 , 코드 정리
  server/src/main/java/com/codestates/julsinsa/auth/dto/LoginDto.java
  server/src/main/java/com/codestates/julsinsa/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/julsinsa/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/codestates/julsinsa/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/codestates/julsinsa/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/julsinsa/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/codestates/julsinsa/cart/controller/CartController.java
  server/src/main/java/com/codestates/julsinsa/cart/dto/CartDto.java
  server/src/main/java/com/codestates/julsinsa/config/PasswordEncoderConfiguration.java
  server/src/main/java/com/codestates/julsinsa/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/julsinsa/helper/email/HtmlEmailSendable.java
  server/src/main/java/com/codestates/julsinsa/item/controller/ItemController.java
  server/src/main/java/com/codestates/julsinsa/item/dto/ItemDto.java
  server/src/main/java/com/codestates/julsinsa/item/entity/Item.java
  server/src/main/java/com/codestates/julsinsa/item/repository/ItemRepository.java
  server/src/main/java/com/codestates/julsinsa/item/service/ItemService.java
  server/src/main/java/com/codestates/julsinsa/member/controller/MemberController.java
  server/src/main/java/com/codestates/julsinsa/member/dto/EmailRequest.java
  server/src/main/java/com/codestates/julsinsa/member/dto/FindDto.java
  server/src/main/java/com/codestates/julsinsa/member/entity/Member.java
  server/src/main/java/com/codestates/julsinsa/review/controller/ReviewController.java
  server/src/main/java/com/codestates/julsinsa/review/dto/ReviewDto.java
  server/src/main/java/com/codestates/julsinsa/review/service/ReviewService.java
Labels: BE, 🛠Refector

#203 Fix: 리뷰 생성 및 수정 처리
  client/src/components/AlcoholDetailPage/AlcohoIItemReview.tsx
  client/src/components/AlcoholDetailPage/AlcohoItemContent.tsx
  client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
  client/src/components/AlcoholDetailPage/ReviewList.tsx
  client/src/pages/ReviewEdit.tsx
  client/src/services/api/axiosInstance.ts
  client/src/types/AlcholInterfaces.ts
Labels: FE, 🐞BugFix

#205 Feat: 주문취소기능 구현 및 가격 정규표현식 적용
  client/src/pages/Mypage/LikeListPage.tsx
  client/src/pages/Mypage/OrderListPage.tsx
Labels: FE, 🔥Feature

#206 Fix: url 수정 env
  client/src/hooks/useAxiosAll.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/pages/Signup/SignupSelection.tsx
  client/src/pages/Signup/SignupTerm.tsx
Labels: FE

#209 Feat: 회원가입, 개인정보 수정 페이지 버그 수정 및 스타일 수정
  client/src/components/Chat/ChatComponent.tsx
  client/src/hooks/useAxiosAll.tsx
  client/src/pages/Mypage/ChangeInfoPage.tsx
  client/src/pages/Signup/SignupInput.tsx
Labels: FE, 🔥Feature, 🐞BugFix, 🎨HTML&CSS

#210 fix : 주문 생성 구현
  server/src/main/java/com/codestates/julsinsa/global/exception/ExceptionCode.java
  server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java
  server/src/main/java/com/codestates/julsinsa/order/controller/OrderController.java
  server/src/main/java/com/codestates/julsinsa/order/dto/ItemOrderDto.java
  server/src/main/java/com/codestates/julsinsa/order/dto/OrderDto.java
  server/src/main/java/com/codestates/julsinsa/order/dto/OrderPostDto.java
  server/src/main/java/com/codestates/julsinsa/order/dto/OrderResponseDto.java
  server/src/main/java/com/codestates/julsinsa/order/entity/Order.java
  server/src/main/java/com/codestates/julsinsa/order/mapper/OrderMapper.java
  server/src/main/java/com/codestates/julsinsa/order/repository/OrderRepository.java
  server/src/main/java/com/codestates/julsinsa/order/service/OrderService.java
  server/src/main/java/com/codestates/julsinsa/review/repository/ReviewRepository.java
  server/src/main/java/com/codestates/julsinsa/review/service/ReviewService.java
  server/src/main/resources/db/h2/data.sql
Labels: BE, 🔥Feature

#211 refactor : 로그인한 사용자를 찾는 컴포넌트 추가
  server/src/main/java/com/codestates/julsinsa/global/utils/MemberUtils.java
Labels: BE, 🛠Refector

#212 Feat: 약관 스크롤 기능 추가 및 브라우저 창 title, ico 추가
  client/public/icon.ico
  client/public/index.html
  client/src/components/SignupTerm/Term.tsx
  client/src/pages/Signup/SignupTerm.tsx
Labels: FE

#215 Feat: 지도 확대율 변화 및 픽업날짜 추가
  client/src/pages/Map.tsx
  client/src/pages/MarkerData.js
  client/src/pages/Mypage/OrderListPage.tsx
Labels: FE, 🔥Feature

#216 Feat: 지도랑 결제연결
  client/src/pages/Place.tsx
Labels: FE

#217 Fix: 한국시간 시간 기준 exp iat 로컬 저장
  client/src/pages/Login/Login.tsx
Labels: FE, 🐞BugFix

#223 refactor : 코드 중복 수정 , import 안쓰는거 제거
  server/src/main/java/com/codestates/julsinsa/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/julsinsa/item/controller/ItemController.java
  server/src/main/java/com/codestates/julsinsa/item/dto/ItemDto.java
  server/src/main/java/com/codestates/julsinsa/item/entity/Favorite.java
  server/src/main/java/com/codestates/julsinsa/item/service/ItemService.java
  server/src/main/java/com/codestates/julsinsa/order/dto/OrderDto.java
  server/src/main/java/com/codestates/julsinsa/review/service/ReviewService.java
  server/src/main/resources/db/h2/data.sql
Labels: BE, 🛠Refector

#221 Refactor: 주류 페이지 리팩토링
  client/src/components/AlcoholDetailPage/AlcohoItemContent.tsx
  client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
  client/src/components/AlcoholPage/AlcoholList.tsx
  client/src/components/AlcoholPage/AlcoholListItem.tsx
  client/src/components/AlcoholPage/Pagination.tsx
  client/src/components/AlcoholPage/SortingUtils.tsx
  client/src/components/Common/ClickFavoriteItem.tsx
  client/src/components/Common/PriceDisplay.tsx
  client/src/components/Common/ReviewRating.tsx
  client/src/pages/Alcohol.tsx
  client/src/services/api/itemAPI.ts
Labels: FE, 🛠Refector

#222 Fix: 디자인 반응형 수정 및 불필요한 라인 삭제 및 정리
  client/src/components/Chat/ChatComponent.tsx
  client/src/components/Common/Button.tsx
  client/src/hooks/useAxiosAll.tsx
  client/src/pages/Login/FindEmail.tsx
  client/src/pages/Login/FindPassword.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Mypage/ChangeInfoPage.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/pages/Signup/SignupSelection.tsx
  client/src/pages/Signup/SignupTerm.tsx
Labels: FE, 🎨HTML&CSS, 🛠Refector

#224 Fix: 여러 버그사항 수정
  client/src/layout/Header/index.tsx
  client/src/pages/Cart.tsx
  client/src/pages/Home.tsx
  client/src/pages/Payment/Payment.tsx
  client/src/pages/Payment/PaymentConfirm.tsx
  client/src/pages/Payment/Paymentitemlist.tsx
  client/src/pages/Payment/Paymentpayinfo.tsx
  client/src/pages/Payment/Progress.tsx
  client/src/pages/Place.tsx
Labels: FE, 🐞BugFix

#225 Feat: 주문취소버튼 비활성화 및 수량표시 제거
  client/src/pages/Map.tsx
  client/src/pages/Mypage/LikeListPage.tsx
  client/src/pages/Mypage/OrderListPage.tsx
  client/src/pages/Place.tsx
Labels: FE, 🔥Feature

#226 Feat: 마커클릭시 매장명 알수있게 설정
  client/src/pages/Mypage/OrderListPage.tsx
  client/src/pages/Place.tsx
Labels: FE, 🔥Feature

#228 Design: 필요없는 border 삭제
  client/src/pages/Place.tsx
Labels: FE, 🎨HTML&CSS

#229 Design: button 컴포넌트 적용 및 세부적인 디자인 수정
  client/src/pages/Mypage/ChangeInfoPage.tsx
Labels: FE, 🎨HTML&CSS

#230 fix : Cart Patch 기능 구현 , 로그인시 passwordIssued 헤더에 담기게 수정
  server/src/main/java/com/codestates/julsinsa/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/codestates/julsinsa/cart/controller/CartController.java
  server/src/main/java/com/codestates/julsinsa/cart/dto/CartDto.java
  server/src/main/java/com/codestates/julsinsa/cart/dto/ItemCartDto.java
  server/src/main/java/com/codestates/julsinsa/cart/service/CartService.java
  server/src/main/java/com/codestates/julsinsa/member/entity/Member.java
Labels: BE, 🔥Feature

#231 Comment: 필요없는 주석 제거 및 정리
  client/src/pages/Mypage/LikeListPage.tsx
  client/src/pages/Mypage/OrderListPage.tsx
Labels: FE

#232 Comment: 파일수정 및 필요없는 코드 삭제
  client/src/layout/Header/Logoutmodal.tsx
  client/src/layout/Header/index.tsx
  client/src/pages/Cart.tsx
  client/src/pages/Home.tsx
  client/src/pages/Payment/CheckoutChang.tsx
  client/src/pages/Payment/Payment.tsx
  client/src/pages/Payment/PaymentConfirm.tsx
  client/src/pages/Payment/PaymentUserinfo.tsx
  client/src/pages/Payment/Paymentitemlist.tsx
  client/src/pages/Payment/Paymentpayinfo.tsx
  client/src/pages/Payment/Progress.tsx
  client/src/pages/Place.tsx
Labels: FE, 🐞BugFix, 🎨HTML&CSS, 🛠Refector

#233 Fix: 페이지 이동 수정
  client/src/pages/ReviewEdit.tsx
Labels: FE, 🐞BugFix

#234 Feat: 에러수정 및 후기버튼 기능 수정
  client/src/pages/Map.tsx
  client/src/pages/Mypage/OrderListPage.tsx
Labels: FE, 🔥Feature, 🐞BugFix

#235 Fix: 버그 수정 및 유효성 추가
  client/src/pages/Mypage/ChangeInfoPage.tsx
  client/src/pages/Signup/SignupInput.tsx
Labels: FE, 🔥Feature, 🐞BugFix

#236 Fix : 비밀번호 수정 로직 변경
  server/src/main/java/com/codestates/julsinsa/member/dto/MemberDto.java
  server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java
  server/src/main/resources/db/h2/data.sql
Labels: BE

#237 fix : Oauth2 리다이렉트 경로 변경
  server/src/main/java/com/codestates/julsinsa/auth/handler/OAuth2MemberSuccessHandler.java
Labels: BE

#239 Feat: 주문내역 최신순으로 나열기능 추가
  client/src/pages/Mypage/OrderListPage.tsx
Labels: FE, 🔥Feature

#240 Fix: 네이버 오어스 수정
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/SignupSelection.tsx
Labels: FE, 🔥Feature, 🐞BugFix

#241 Feat : 네이버 OAuth2 구현
  server/src/main/java/com/codestates/julsinsa/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/resources/db/h2/data.sql
Labels: BE, 🔥Feature

#244 Fix: 데이터 변경
  client/src/components/AlcoholDetailPage/AlcohoItemContent.tsx
  client/src/types/AlcholInterfaces.ts
Labels: FE, 🐞BugFix

#247 Feat: 마이페이지 주류상세페이지 연결 등 기능 구현
  client/src/pages/Mypage/LikeListPage.tsx
  client/src/pages/Mypage/OrderListPage.tsx
Labels: FE, 🔥Feature, 🐞BugFix

#248 Design: 메인페이지 css 수정
  client/src/pages/Home.tsx
  client/src/pages/Homelayout.tsx
Labels: FE, 🎨HTML&CSS

#253 Refactor: 코드 정리
  client/src/services/api/axiosInstance.ts
  client/src/services/api/itemAPI.ts
Labels: FE, 🛠Refector

#254 Feat: 찜리스트 목록없음 알림 기능 구현 및 주문내역페이지 에러 수정
  client/src/pages/Mypage/LikeListPage.tsx
  client/src/pages/Mypage/OrderListPage.tsx
Labels: FE, 🔥Feature, 🐞BugFix

#256 Fix: 페이지네이션 오류 해결
  client/src/pages/Mypage/LikeListPage.tsx
  client/src/pages/Mypage/OrderListPage.tsx
Labels: FE, 🐞BugFix

#261 fix: 기타 버그 수정
  client/src/hooks/useAxiosAll.tsx
  client/src/pages/Login/FindPassword.tsx
  client/src/pages/Mypage/ChangeInfoPage.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/pages/Signup/SignupTerm.tsx
Labels: FE, 🐞BugFix

#262 Fix : 파일 업로드시 임시파일 생성 안되게 설정
  server/src/main/java/com/codestates/julsinsa/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/codestates/julsinsa/image/service/ImageService.java
  server/src/main/java/com/codestates/julsinsa/image/service/UploadImageS3.java
  server/src/main/resources/db/h2/data.sql
Labels: BE, 🔥Feature

#263 Fix: text 수정 및 header 수정
  client/src/hooks/useAxiosAll.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/pages/Signup/SignupTerm.tsx
Labels: FE, 🐞BugFix

#264 Feat: 검색 기능 추가
  client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
  client/src/components/AlcoholPage/ItemSearch.tsx
  client/src/components/AlcoholPage/Pagination.tsx
  client/src/pages/Alcohol.tsx
  client/src/services/api/axiosInstance.ts
  client/src/services/api/itemAPI.ts
  client/src/styles/GlobalStyle.ts
  client/src/types/AlcholInterfaces.ts
Labels: FE, 🔥Feature

#265 Fix: 긴급 수정
  client/src/pages/Mypage/ChangeInfoPage.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/pages/Signup/SignupTerm.tsx
Labels: FE

#267 Fix : 결제시 재고변경 , 이메일 인증 비동기 -> 동기
  server/src/main/java/com/codestates/julsinsa/chatai/config/ChatGptConfig.java
  server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java
  server/src/main/java/com/codestates/julsinsa/order/service/OrderService.java
Labels: BE, 🔥Feature

#268 Refactor: 주석 제거
  client/src/components/AlcoholPage/ItemSearch.tsx
  client/src/components/Common/ClickFavoriteItem.tsx
  client/src/pages/Alcohol.tsx
Labels: FE, 🛠Refector

#266 Design: map 커스텀오버레이 css변경
  client/src/pages/Map.tsx
Labels: FE, 🎨HTML&CSS

#269 Fix : gpt api키 위치 수정
  server/src/main/java/com/codestates/julsinsa/chatai/config/ChatGptConfig.java
  server/src/main/java/com/codestates/julsinsa/chatai/service/ChatGptService.java
Labels: BE

#272 Fix: 오어스 버그 수정
  client/src/hooks/useAxiosAll.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Mypage/ChangeInfoPage.tsx
  client/src/pages/Signup/SignupInput.tsx
Labels: FE, 🐞BugFix

#273 Feat: 지도페이지 선택박스부분수정, 첫화면 상단부고정 기능 추가
  client/src/pages/Place.tsx
Labels: FE, 🔥Feature

#274 Fix: 상품 검색 총 개수 수정
  client/src/components/AlcoholPage/ItemSearch.tsx
  client/src/pages/Alcohol.tsx
Labels: FE, 🐞BugFix

#275 Fix: 기타 버그 수정
  client/src/components/Chat/ChatComponent.tsx
  client/src/components/Common/AlertModal.tsx
  client/src/components/Common/Button.tsx
  client/src/pages/Login/FindEmail.tsx
  client/src/pages/Mypage/ChangeInfoPage.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/pages/Signup/SignupTerm.tsx
  client/src/types/Interfaces.ts
Labels: FE, 🐞BugFix

#277 Fix:버그수정
  client/src/pages/Mypage/ChangeInfoPage.tsx
Labels: FE, 🐞BugFix

#279 Fix: 주류 검색 수정
  client/src/components/AlcoholPage/ItemSearch.tsx
  client/src/pages/Alcohol.tsx
Labels: FE, 🐞BugFix

#281 fix: 전화번호 유효성 검사 추가
  client/src/pages/Mypage/ChangeInfoPage.tsx
  client/src/pages/Signup/SignupInput.tsx
Labels: FE, 🐞BugFix

#283 fix: 버그 수정 및 스타일 수정
  client/src/components/Chat/ChatComponent.tsx
  client/src/components/HelpCenter/AnswerContainer.tsx
  client/src/pages/HelpCenter.tsx
  client/src/pages/Login/FindEmail.tsx
  client/src/pages/Login/FindPassword.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/SignupInput.tsx
Labels: FE, 🐞BugFix, 🎨HTML&CSS

#285 Refactor: 주류 리스트 및 상세 웹 반응형 수정
  client/src/components/AlcoholDetailPage/AlcohoIItemReview.tsx
  client/src/components/AlcoholDetailPage/AlcohoItemContent.tsx
  client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
  client/src/components/AlcoholDetailPage/ReviewList.tsx
  client/src/components/AlcoholPage/AlcoholList.tsx
  client/src/components/AlcoholPage/AlcoholListItem.tsx
  client/src/components/AlcoholPage/ItemSearch.tsx
  client/src/components/AlcoholPage/Pagination.tsx
  client/src/components/AlcoholPage/SortingUtils.tsx
  client/src/components/Common/ReviewRating.tsx
  client/src/pages/Alcohol.tsx
Labels: FE, 🎨HTML&CSS, 🛠Refector

#286 Fix: 상품 디테일 수정
  client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
Labels: FE, 🐞BugFix

#287 Fix: 스타일 수정
  client/src/components/Chat/ChatComponent.tsx
  client/src/pages/Login/FindEmail.tsx
  client/src/pages/Login/FindPassword.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/SignupInput.tsx
  client/src/pages/Signup/SignupSelection.tsx
  client/src/pages/Signup/SignupTerm.tsx
Labels: FE, 🎨HTML&CSS

#288 Fix: gpt 색상 gray로 변경
  client/src/components/Chat/ChatComponent.tsx
Labels: FE, 🎨HTML&CSS

#291 Design: 후기 페이지 디자인 수정
  client/src/layout/Header/index.tsx
  client/src/pages/ReviewEdit.tsx
  client/src/styles/GlobalStyle.ts
Labels: FE, 🎨HTML&CSS

#293 Fix: 헤더 오버 수정
  client/src/layout/Header/index.tsx
  client/src/styles/GlobalStyle.ts
Labels: FE, 🐞BugFix, 🎨HTML&CSS

#294 Fix: 헤더 추가 수정
  client/src/components/AlcoholPage/SortingUtils.tsx
  client/src/layout/Header/index.tsx
  client/src/pages/Alcohol.tsx
Labels: FE, 🐞BugFix

#304 Refactor: 전체적인 부분 수정
  client/public/index.html
  client/src/assets/fonts/IBMPlexSansKR-Bold.woff
  client/src/assets/fonts/IBMPlexSansKR-ExtraLight.woff
  client/src/assets/fonts/IBMPlexSansKR-Light.woff
  client/src/assets/fonts/IBMPlexSansKR-Medium.woff
  client/src/assets/fonts/IBMPlexSansKR-Regular.woff
  client/src/assets/fonts/IBMPlexSansKR-SemiBold.woff
  client/src/assets/fonts/IBMPlexSansKR-Thin.woff
  client/src/assets/fonts/PoetsenOne-Regular.woff
  client/src/pages/Login/Login.tsx
  client/src/pages/Mypage/LikeListPage.tsx
  client/src/pages/Mypage/OrderListPage.tsx
  client/src/pages/Place.tsx
  client/src/pages/Signup/SignupSelection.tsx
  client/src/styles/GlobalStyle.ts
  client/src/styles/font.css
  client/src/utils/priceUtils.ts
Labels: FE, 🛠Refector
